$foreground = rgb(d2dae4)
$backgroundCol = rgb(070412)
$color0 = rgb(070412)
$color1 = rgb(365B85)
$color2 = rgb(546E92)
$color3 = rgb(BF6491)
$color4 = rgb(718EAF)
$color5 = rgb(9F9BB7)
$color6 = rgb(9EB3CB)
$color7 = rgb(d2dae4)
$color8 = rgb(93989f)
$color9 = rgb(365B85)
$color10 = rgb(546E92)
$color11 = rgb(BF6491)
$color12 = rgb(718EAF)
$color13 = rgb(9F9BB7)
$color14 = rgb(9EB3CB)
$color15 = rgb(d2dae4)
