### SvartOS ###
# Hyprland config 

$config = $HOME/.config/hypr/config 

source = $config/env.conf 
source = $config/init.conf

source = $config/monitors.conf 
source = $config/settings.conf 
source = $config/layouts.conf 
source = $config/visuals.conf 
source = $config/windowrules.conf
source = $config/permissions.conf

source = $config/keybinds.conf 

