# Preload images
#preload = /home/svartorm/.config/wallpapers/daddydeathwolf.png
preload = /home/svartorm/.config/wallpapers/rebellious_tower.png
#preload = /home/svartorm/.config/wallpapers/hanged_man_tree.jpg
#preload = path/to/other.png

# Set wallpaper
#wallpaper = ,/home/svartorm/.config/wallpapers/daddydeathwolf.png
wallpaper = ,/home/svartorm/.config/wallpapers/rebellious_tower.png
#wallpaper = ,/home/svartorm/.config/wallpapers/hanged_man_tree.jpg
# Can set it to a specific monitor using wallpaper = monitorname, path/to/image.png (hyprctl monitors to get the name)

splash = false

ipc = on
